#include<stdio.h>
main()
{
    long long int n,k,l=0,i,j=-1,p,a;
    scanf("%lld%lld",&n,&k);
    if(n%2==0)
    {
        for(i=1;i<=n;i++)
        {
            if(i<=n/2)
            {
                j=j+2;
                if(i==k)
                   {
                    a=j;
                   break;
                   }
            }
            if(i>n/2)
            {
               l=l+2;
               if(i==k)
               {
                   a=l;
                break;
               }
            }
        }
    }
    if(n%2!=0)
    {
        for(i=1;i<=n;i++)
        {
            if(i<=n/2+1)
            {
                j=j+2;
                if(i==k)
                   {
                    a=j;
                   break;
                   }
            }
            if(i>n/2+1)
            {
               l=l+2;
               if(i==k)
               {
                   a=l;
                break;
               }
            }
        }
    }
    printf("%lld",a);
}
